/* AUTO-GENERATED FILE. DO NOT EDIT! */
import 'image_encoder.dart';

/// Printer model enum
enum PrinterModel {
  unknown('UNKNOWN'),
  a20('A20'),
  a203('A203'),
  a63('A63'),
  a8('A8'),
  a8P('A8_P'),
  b1('B1'),
  b11('B11'),
  b16('B16'),
  b18('B18'),
  b18s('B18S'),
  b2('B2'),
  b203('B203'),
  b21('B21'),
  b21Pro('B21_PRO'),
  b21C2b('B21_C2B'),
  b21L2b('B21_L2B'),
  b21s('B21S'),
  b21sC2b('B21S_C2B'),
  b3('B3'),
  b31('B31'),
  b32('B32'),
  b32r('B32R'),
  b3s('B3S'),
  b3sP('B3S_P'),
  b4('B4'),
  b50('B50'),
  b50w('B50W'),
  betty('BETTY'),
  c1('C1'),
  d101('D101'),
  d11('D11'),
  d11H('D11_H'),
  d11Pro('D11_PRO'),
  d110('D110'),
  d110M('D110_M'),
  d11s('D11S'),
  d41('D41'),
  d61('D61'),
  dxx('DXX'),
  ep2mH('EP2M_H'),
  et10('ET10'),
  fust('FUST'),
  h1('H1'),
  h1s('H1S'),
  hiD110('HI_D110'),
  hiNbD11('HI_NB_D11'),
  jcM90('JC_M90'),
  jcb3s('JCB3S'),
  k2('K2'),
  k3('K3'),
  k3W('K3_W'),
  m2H('M2_H'),
  m3('M3'),
  mp3k('MP3K'),
  mp3kW('MP3K_W'),
  n1('N1'),
  p1('P1'),
  p18('P18'),
  p1s('P1S'),
  s1('S1'),
  s3('S3'),
  s6('S6'),
  s6P('S6_P'),
  t2s('T2S'),
  t6('T6'),
  t7('T7'),
  t8('T8'),
  t8s('T8S'),
  tp2mH('TP2M_H'),
  z401('Z401');

  const PrinterModel(this.value);
  final String value;
}

/// Printer model metadata
class PrinterModelMeta {
  final PrinterModel model;
  final List<int> id;
  final int dpi;
  final PrintDirection printDirection;
  final int printheadPixels;
  final List<int> paperTypes;
  final int densityMin;
  final int densityMax;
  final int densityDefault;

  const PrinterModelMeta({
    required this.model,
    required this.id,
    required this.dpi,
    required this.printDirection,
    required this.printheadPixels,
    required this.paperTypes,
    required this.densityMin,
    required this.densityMax,
    required this.densityDefault,
  });
}

/// Printer models library
const List<PrinterModelMeta> modelsLibrary = [
  PrinterModelMeta(
    model: PrinterModel.a20,
    id: [2817],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 400,
    paperTypes: [1, 2, 4], // WithGaps, Black, Transparent
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.a203,
    id: [2818],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 400,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.a63,
    id: [2054],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 851,
    paperTypes: [1, 4, 2],
    densityMin: 1,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.a8,
    id: [256],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 576,
    paperTypes: [2, 1, 3],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.a8P,
    id: [273],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 576,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b1,
    id: [4096],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b11,
    id: [51457],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5, 4],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.b16,
    id: [1792],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.b18,
    id: [3584],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4, 6, 7, 3],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.b18s,
    id: [3585],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4, 6, 7, 3],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.b2,
    id: [6912],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 432,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b203,
    id: [2816],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 400,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b21,
    id: [768],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b21Pro,
    id: [785],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 591,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b21C2b,
    id: [771, 775],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 3, 4, 2],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b21L2b,
    id: [769],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b21s,
    id: [777],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b21sC2b,
    id: [776],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b3,
    id: [52993],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 600,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b31,
    id: [5632],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 600,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b32,
    id: [2049],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 851,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.b32r,
    id: [2050],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 851,
    paperTypes: [1],
    densityMin: 1,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.b3s,
    id: [256, 260, 262],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 576,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b3sP,
    id: [272],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 576,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b4,
    id: [6656],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 832,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.b50,
    id: [51713],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 400,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.b50w,
    id: [51714],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.betty,
    id: [2561],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 192,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.c1,
    id: [5120],
    dpi: 300,
    printDirection: PrintDirection.left,
    printheadPixels: 178,
    paperTypes: [3],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.d101,
    id: [2560],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 192,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.d11,
    id: [512],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.d11H,
    id: [528],
    dpi: 300,
    printDirection: PrintDirection.left,
    printheadPixels: 142,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.d11Pro,
    id: [531],
    dpi: 300,
    printDirection: PrintDirection.left,
    printheadPixels: 142,
    paperTypes: [4, 1],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.d110,
    id: [2304, 2305],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.d110M,
    id: [2320],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.d11s,
    id: [514],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.ep2mH,
    id: [4610],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 567,
    paperTypes: [1, 4, 2, 6],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.et10,
    id: [5376],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 1600,
    paperTypes: [3],
    densityMin: 3,
    densityMax: 3,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.fust,
    id: [513],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.h1,
    id: [3840],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.h1s,
    id: [4352],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 3, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.hiD110,
    id: [2305],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 120,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.hiNbD11,
    id: [512],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 120,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.jcM90,
    id: [51461],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.jcb3s,
    id: [256],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 576,
    paperTypes: [1, 2, 3, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.k2,
    id: [6144],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 448,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.k3,
    id: [4864],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 640,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.k3W,
    id: [4865],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 640,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.m2H,
    id: [4608],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 567,
    paperTypes: [1, 4, 2, 6],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.m3,
    id: [6400],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 851,
    paperTypes: [1, 4, 2, 6],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.mp3k,
    id: [4866],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 640,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.mp3kW,
    id: [4867],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 640,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.n1,
    id: [3586],
    dpi: 203,
    printDirection: PrintDirection.left,
    printheadPixels: 96,
    paperTypes: [1, 7, 4, 6, 3],
    densityMin: 1,
    densityMax: 3,
    densityDefault: 2,
  ),
  PrinterModelMeta(
    model: PrinterModel.p1,
    id: [1024],
    dpi: 300,
    printDirection: PrintDirection.left,
    printheadPixels: 697,
    paperTypes: [8],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.p18,
    id: [1026],
    dpi: 300,
    printDirection: PrintDirection.left,
    printheadPixels: 662,
    paperTypes: [8],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.p1s,
    id: [1025],
    dpi: 300,
    printDirection: PrintDirection.left,
    printheadPixels: 662,
    paperTypes: [8],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.s1,
    id: [51458],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.s3,
    id: [51460],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.s6,
    id: [261, 259, 258, 257],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 576,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.s6P,
    id: [274],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 600,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.t2s,
    id: [53250],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 832,
    paperTypes: [1, 2],
    densityMin: 1,
    densityMax: 20,
    densityDefault: 15,
  ),
  PrinterModelMeta(
    model: PrinterModel.t6,
    id: [51715],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.t7,
    id: [51717],
    dpi: 203,
    printDirection: PrintDirection.top,
    printheadPixels: 384,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.t8,
    id: [51718],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 567,
    paperTypes: [1, 2, 3, 5],
    densityMin: 6,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.t8s,
    id: [2053],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 851,
    paperTypes: [1],
    densityMin: 1,
    densityMax: 15,
    densityDefault: 10,
  ),
  PrinterModelMeta(
    model: PrinterModel.tp2mH,
    id: [4609],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 591,
    paperTypes: [1, 2, 4],
    densityMin: 1,
    densityMax: 5,
    densityDefault: 3,
  ),
  PrinterModelMeta(
    model: PrinterModel.z401,
    id: [2051],
    dpi: 300,
    printDirection: PrintDirection.top,
    printheadPixels: 851,
    paperTypes: [1, 4],
    densityMin: 1,
    densityMax: 15,
    densityDefault: 10,
  ),
];

/// Get printer metadata by ID
PrinterModelMeta? getPrinterMetaById(int id) {
  try {
    return modelsLibrary.firstWhere((meta) => meta.id.contains(id));
  } catch (e) {
    return null;
  }
}

/// Get printer metadata by model
PrinterModelMeta? getPrinterMetaByModel(PrinterModel model) {
  try {
    return modelsLibrary.firstWhere((meta) => meta.model == model);
  } catch (e) {
    return null;
  }
}

/// Get all model prefixes for scanning (e.g., ['A2', 'B1', 'D1'])
/// Same as React Native: getAllModelPrefixes()
List<String> getAllModelPrefixes({int length = 2}) {
  final prefixes = modelsLibrary
      .map((meta) => meta.model.name
          .toUpperCase()
          .substring(0, length.clamp(1, meta.model.name.length)))
      .toSet()
      .toList();
  prefixes.sort();
  return prefixes;
}
